// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBggCPr16g_2nyx94I7krjsqRRxvoNI5k',
    appId: '1:984721519508:web:9bf9cc3d44f643b9959581',
    messagingSenderId: '984721519508',
    projectId: 'contactsmanagement-dcb0c',
    authDomain: 'contactsmanagement-dcb0c.firebaseapp.com',
    databaseURL: 'https://contactsmanagement-dcb0c-default-rtdb.firebaseio.com',
    storageBucket: 'contactsmanagement-dcb0c.firebasestorage.app',
    measurementId: 'G-Q25XBLRG4S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxo_QcZHGleyTtytsAsoE7IIddnsiQCxQ',
    appId: '1:984721519508:android:5941d400e8e45de2959581',
    messagingSenderId: '984721519508',
    projectId: 'contactsmanagement-dcb0c',
    databaseURL: 'https://contactsmanagement-dcb0c-default-rtdb.firebaseio.com',
    storageBucket: 'contactsmanagement-dcb0c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDO002EitzgFQDOi0ZkP8GZu7lhnlOrUY8',
    appId: '1:984721519508:ios:340daae1acdde46a959581',
    messagingSenderId: '984721519508',
    projectId: 'contactsmanagement-dcb0c',
    databaseURL: 'https://contactsmanagement-dcb0c-default-rtdb.firebaseio.com',
    storageBucket: 'contactsmanagement-dcb0c.firebasestorage.app',
    iosBundleId: 'com.contactio.app',
  );
}
